repos:
-   repo: local
    hooks:
    -   id: black
        name: black
        entry: black
        language: system
        types : ["file", "python"]

-   repo: local
    hooks:
    -   id: system
        name: PyLint
        entry: pylint
        language: system
        files: \.py$
        args:
            [
                "-sn"
            ]